import React from 'react';
import PageTransation from '../components/PageTransation';

const LegalPage = ({ title, content }) => {
    return (
        <PageTransation>
            <div className="container mx-auto px-4 w-[90%] max-w-[900px] py-20">
                <h1 className="text-4xl font-bold text-heading mb-10 text-center">{title}</h1>
                <div className="prose prose-blue max-w-none text-p leading-relaxed space-y-6 bg-white p-8 md:p-12 rounded-3xl shadow-sm border border-black/5">
                    {content || (
                        <>
                            <section>
                                <h2 className="text-2xl font-semibold text-heading mb-4">1. Introduction</h2>
                                <p>Welcome to the E-Commerce Market Dynamics & XAI Forecasting Engine. These terms and policies govern your use of our predictive analytics platform and services.</p>
                            </section>
                            <section>
                                <h2 className="text-2xl font-semibold text-heading mb-4">2. Data Privacy</h2>
                                <p>We take your data security seriously. Our XAI models process market data while ensuring that personal identifiers are protected and handled according to global standards.</p>
                            </section>
                            <section>
                                <h2 className="text-2xl font-semibold text-heading mb-4">3. Market Predictions</h2>
                                <p>All forecasts provided are generated by AI models based on historical trends. While we strive for high accuracy, market dynamics are volatile and predictions should be used as a supplementary decision-making tool.</p>
                            </section>
                            <section>
                                <h2 className="text-2xl font-semibold text-heading mb-4">4. Intellectual Property</h2>
                                <p>The algorithms, XAI visualizations, and data structures are the property of Market XAI Forecasting Engine.</p>
                            </section>
                        </>
                    )}
                </div>
            </div>
        </PageTransation>
    );
};

export default LegalPage;
